/**
 * Phrases d'encouragement affichées au démarrage de l'application.
 *
 * Une phrase est tirée à chaque ouverture, sans répétition : toutes les
 * phrases défilent avant qu'une seule ne revienne (cf. lib/encouragement.ts).
 *
 * Le ton est volontairement doux et jamais culpabilisant : ce sont des
 * encouragements, pas des injonctions à la performance.
 */
export const ENCOURAGEMENTS: readonly string[] = [
  'Tu es plus capable que tu ne le crois aujourd’hui.',
  'Tu n’as pas besoin d’être parfaite pour avancer.',
  'Ce que tu apprends aujourd’hui construit la personne que tu deviens.',
  'Tu as déjà surmonté des journées qui te semblaient impossibles.',
  'Ta valeur ne dépend pas d’une note.',
  'Tu peux avoir des doutes et continuer quand même.',
  'Tu mérites d’être fière de tous les efforts que tu fais.',
  'Tu as le droit d’apprendre à ton rythme.',
  'Tu n’as pas besoin de tout savoir pour être légitime.',
  'Chaque compétence que tu maîtrises aujourd’hui a commencé par une difficulté.',
  'Tu es capable de comprendre des choses qui te paraissent compliquées au premier regard.',
  'Fais confiance à tout le travail que tu as déjà fourni.',
  'Tu peux être ambitieuse sans te mettre une pression impossible.',
  'Tes erreurs ne retirent rien à ton intelligence.',
  'Tu as le droit d’être fière de toi avant même d’avoir atteint ton objectif.',
  'Tu n’es pas en retard : tu es en train d’avancer.',
  'Tu peux apprendre, t’adapter et recommencer autant de fois qu’il le faut.',
  'Tu es beaucoup plus solide que la petite voix qui te fait douter.',
  'Tu as déjà en toi une grande partie de ce qu’il te faut pour réussir.',
  'Ta progression mérite d’être regardée avec autant d’attention que tes difficultés.',
  'Tu n’as rien à prouver en une seule journée.',
  'Crois un peu plus en la version de toi qui continue d’essayer.',
  'Tu peux être stressée et compétente en même temps.',
  'Le doute est un sentiment, pas une preuve de ton incapacité.',
  'Tu as le droit de te sentir fière du chemin déjà parcouru.',
  'Commence par cinq minutes : l’élan viendra ensuite.',
  'Une petite session de travail vaut mieux qu’une grande session repoussée à demain.',
  'Aujourd’hui n’a pas besoin d’être parfait pour être utile.',
  'Un chapitre, une fiche, une page : chaque pas compte.',
  'Le plus difficile est parfois simplement de commencer.',
  'Tu n’as pas besoin d’être motivée pour faire un petit pas.',
  'Fais juste la prochaine chose utile, pas toute la montagne d’un coup.',
  'Ton futur toi sera contente que tu aies commencé aujourd’hui.',
  'Une heure bien utilisée peut changer toute une journée.',
  'Même une journée moyenne peut contenir un très bon moment de travail.',
  'Tu peux transformer une journée qui démarre mal en journée satisfaisante.',
  'Ce que tu fais régulièrement compte plus que ce que tu fais exceptionnellement.',
  'Le bon moment pour reprendre, c’est maintenant, même doucement.',
  'Tu n’as pas besoin d’attendre d’avoir envie pour te lancer.',
  'Aujourd’hui est une nouvelle occasion de te rapprocher de ton objectif.',
  'Une tâche terminée enlève toujours un peu de poids à ta tête.',
  'Avance avec l’énergie que tu as, pas avec celle que tu aimerais avoir.',
  'Tu peux faire beaucoup avec une série de petits efforts.',
  'Rends cette journée un peu meilleure grâce à une seule action utile.',
  'Tu n’as pas besoin d’un grand déclic : juste d’un premier mouvement.',
  'Ce que tu commences aujourd’hui sera plus facile à continuer demain.',
  'Ta motivation peut venir après l’action, pas forcément avant.',
  'Une petite victoire peut suffire à relancer toute ta journée.',
  'Choisis une tâche simple, termine-la, puis construis à partir de là.',
  'Tu es à une décision de commencer quelque chose dont tu seras fière ce soir.',
  'Pendant quelques minutes, une seule chose compte : ce que tu fais maintenant.',
  'Tu n’as pas besoin de penser à tout en même temps.',
  'Un exercice à la fois, une page à la fois, une idée à la fois.',
  'Pose le reste de côté et donne toute ton attention à la prochaine étape.',
  'Ton cerveau travaille mieux quand tu lui donnes une mission claire.',
  'Tu peux revenir à ta tâche autant de fois que ton attention s’échappe.',
  'Se reconcentrer fait partie du travail, ce n’est pas un échec.',
  'Éloigne le bruit, garde l’essentiel.',
  'Vingt minutes de vraie concentration peuvent être très puissantes.',
  'Il suffit parfois d’un bureau dégagé et d’un objectif précis pour repartir.',
  'Ferme ce qui ne sert pas, ouvre ce qui te fait avancer.',
  'Tu n’as pas à finir tout le programme maintenant : concentre-toi sur cette partie.',
  'Ton attention est précieuse : choisis où tu veux la mettre.',
  'Respire, relis la consigne et avance étape par étape.',
  'Quand tout semble confus, reviens à la question la plus simple : qu’est-ce que je dois faire maintenant ?',
  'La concentration n’a pas besoin d’être parfaite pour être productive.',
  'Un téléphone loin de toi peut devenir dix minutes de concentration en plus.',
  'Donne-toi une courte période sans interruption et vois jusqu’où tu peux aller.',
  'Tu peux toujours recommencer une session, même après t’être dispersée.',
  'Moins de choses à la fois, plus de progrès au final.',
  'Tu n’as pas besoin de te dépêcher pour avancer efficacement.',
  'Prends le temps de comprendre avant de vouloir terminer.',
  'Une idée bien comprise vaut mieux que dix pages lues trop vite.',
  'Ton seul objectif pour l’instant est d’être présente dans ce que tu fais.',
  'Fais de la prochaine demi-heure un petit espace réservé à toi et à ton objectif.',
  'Tu n’as pas besoin d’aller vite pour aller loin.',
  'Chaque fois que tu comprends quelque chose de nouveau, tu progresses.',
  'Les progrès discrets sont toujours des progrès.',
  'Ce qui te demande beaucoup d’effort aujourd’hui pourra devenir naturel demain.',
  'Tu n’es pas censée tout maîtriser dès la première fois.',
  'Apprendre, c’est souvent ne pas comprendre puis comprendre un peu mieux.',
  'Une erreur corrigée est une connaissance gagnée.',
  'Tu progresses aussi les jours où ça ne se voit pas encore.',
  'Compare-toi surtout à ce que tu savais hier.',
  'Chaque révision rend le chemin un peu plus familier.',
  'Tu construis tes connaissances couche après couche.',
  'Un concept difficile aujourd’hui peut devenir évident après quelques répétitions.',
  'Tu peux avoir l’impression de stagner alors que ton cerveau est en train de consolider.',
  'La régularité transforme les petites avancées en grandes différences.',
  'Tes efforts d’aujourd’hui s’additionnent à ceux d’hier.',
  'Ce n’est pas grave si tu dois relire : relire, c’est apprendre aussi.',
  'Chaque question que tu poses montre que tu avances vers une meilleure compréhension.',
  'Tu n’as pas besoin de voir immédiatement le résultat pour que ton travail soit utile.',
  'La progression n’est pas une ligne droite, et elle reste une progression.',
  'Les bases que tu renforces aujourd’hui te feront gagner du temps demain.',
  'Tu peux être fière d’avoir compris 10 % de plus qu’hier.',
  'Un petit progrès répété finit par devenir un grand changement.',
  'Continue d’empiler les petites victoires.',
  'Tu apprends même lorsque le résultat n’est pas encore visible.',
  'Ta constance est en train de construire quelque chose de solide.',
  'Un examen mesure une performance à un moment donné, pas ta valeur.',
  'Tu n’as pas besoin de tout savoir pour bien réussir.',
  'Lis calmement, commence par ce que tu maîtrises et construis à partir de là.',
  'Tu as travaillé pour ce moment : laisse ton cerveau faire sa part.',
  'Une question difficile n’annule pas toutes celles que tu sais faire.',
  'Tu peux prendre quelques secondes pour réfléchir avant de répondre.',
  'Le stress peut être présent sans prendre le contrôle.',
  'Concentre-toi sur les points que tu peux gagner, un par un.',
  'Tu n’es pas obligée de sortir en sachant exactement quelle note tu auras.',
  'Fais au mieux avec ce que tu sais aujourd’hui : c’est suffisant.',
  'Une copie n’a pas besoin d’être parfaite pour être bonne.',
  'Quand une question bloque, avance puis reviens-y avec un regard neuf.',
  'Tu peux transformer ton stress en attention.',
  'Ton travail ne disparaît pas au moment où l’épreuve commence.',
  'Tu connais probablement plus de choses que ton stress ne veut te laisser croire.',
  'Le premier réflexe : lire, respirer, organiser.',
  'Ne laisse pas une question te faire oublier tout ce que tu maîtrises.',
  'Chaque réponse claire vaut mieux qu’une réponse précipitée.',
  'Tu peux réussir même sans te sentir totalement prête.',
  'Le calme se construit question après question.',
  'Tu n’as qu’une seule chose à faire : donner le meilleur disponible aujourd’hui.',
  'Ce contrôle est une étape, pas un verdict sur ton avenir.',
  'Fais confiance à tes révisions et à ta capacité de raisonner.',
  'Tu as le droit d’être stressée avant une épreuve et de très bien t’en sortir.',
  'Une note est une information pour la suite, jamais une définition de toi.',
  'Tu peux ralentir sans abandonner.',
  'Une journée difficile ne prédit pas la suite de ta semaine.',
  'Faire le minimum utile est parfois déjà une vraie victoire.',
  'Tu as le droit d’être fatiguée et de prendre soin de toi.',
  'Aujourd’hui, avance avec douceur plutôt qu’avec culpabilité.',
  'Si tout paraît trop lourd, réduis l’objectif jusqu’à ce qu’il devienne possible.',
  'Tu n’as pas besoin de rattraper toute ta vie en une soirée.',
  'Un mauvais jour n’efface pas tous les bons efforts précédents.',
  'Tu peux recommencer ta journée à 10 h, 14 h ou même 20 h.',
  'Le repos fait aussi partie d’un travail durable.',
  'Quand ton énergie est basse, choisis la simplicité.',
  'Tu n’as pas échoué parce que tu as besoin d’une pause.',
  'Parfois, la meilleure décision est de faire moins, mais de le faire bien.',
  'Sois aussi patiente avec toi que tu le serais avec quelqu’un que tu aimes.',
  'Ce qui paraît énorme maintenant sera peut-être beaucoup plus simple après une pause.',
  'Tu n’as pas besoin de transformer chaque journée en performance.',
  'Même aujourd’hui, il existe probablement une petite chose que tu peux réussir.',
  'Tu peux mettre de côté la culpabilité et garder seulement la prochaine étape.',
  'Tu n’as pas à être forte tout le temps pour continuer d’avancer.',
  'Accorde-toi le droit d’avoir une journée imparfaite.',
  'Une pause intelligente peut sauver le reste de ta journée.',
  'Ton énergie mérite d’être gérée, pas jugée.',
  'Si ton cerveau dit stop, écoute-le un moment puis reviens doucement.',
  'Les journées lentes comptent elles aussi dans le parcours.',
  'Demain ne sera pas obligé de ressembler à aujourd’hui.',
  'Écris trois priorités : tout le reste peut attendre son tour.',
  'Un plan simple vaut mieux qu’une liste impossible.',
  'Ce qui est écrit prend moins de place dans ta tête.',
  'Commence par ce qui est important, pas par ce qui crie le plus fort.',
  'Découpe une grosse tâche jusqu’à ce que la première étape paraisse facile.',
  'Ton agenda est un outil pour t’aider, pas pour te juger.',
  'Prévoir une pause, c’est aussi s’organiser.',
  'Tu n’as pas besoin de remplir chaque minute pour avoir une journée productive.',
  'Une tâche avec une heure précise a plus de chances d’être faite.',
  'Fais de la place pour l’imprévu : les plans respirent mieux comme ça.',
  'Choisis ce qui mérite vraiment ton énergie aujourd’hui.',
  'Commencer par cinq minutes de rangement peut clarifier toute une session de travail.',
  'Un petit plan du matin peut éviter beaucoup de stress le soir.',
  'Tu peux changer ton planning sans avoir raté ta journée.',
  'Prioriser, c’est accepter que tout ne soit pas urgent.',
  'Regroupe les petites tâches pour garder de l’énergie mentale.',
  'Un objectif précis est plus facile à atteindre qu’un vague “je dois travailler”.',
  'Décide à l’avance quand tu t’arrêtes : cela aide aussi à mieux commencer.',
  'Prépare le matériel dont tu as besoin avant de lancer ta session.',
  'L’organisation sert à te simplifier la vie, pas à la rendre rigide.',
  'Fais d’abord ce qui débloque le reste.',
  'Une liste courte et réaliste peut être extrêmement efficace.',
  'Tu peux déplacer une tâche sans la fuir : il suffit de lui donner un nouveau moment.',
  'Quand tu sais quoi faire ensuite, ton cerveau dépense moins d’énergie à hésiter.',
  'Ton planning doit travailler pour toi, pas l’inverse.',
  'Tu n’as pas besoin de ne jamais tomber : tu as seulement besoin de te relever encore une fois.',
  'Continuer doucement reste continuer.',
  'Les difficultés ne signifient pas que tu n’es pas faite pour ça.',
  'Tu peux recommencer autant de fois que nécessaire.',
  'Ce qui résiste aujourd’hui peut céder avec une autre méthode demain.',
  'Ton effort compte même quand personne ne le voit.',
  'Ne juge pas tout ton parcours à partir d’un seul obstacle.',
  'Tu peux changer de méthode sans changer d’objectif.',
  'Une période compliquée n’efface pas ta capacité à réussir.',
  'Le courage, c’est parfois simplement ouvrir le cours une nouvelle fois.',
  'Chaque fois que tu reviens après avoir eu envie d’abandonner, tu renforces quelque chose.',
  'Tu n’as pas besoin d’aimer chaque étape pour aller jusqu’au bout.',
  'Les choses importantes demandent parfois plusieurs essais.',
  'Tu peux faire une pause sans quitter le chemin.',
  'Ton rythme peut changer, ton objectif peut rester.',
  'Les détours font aussi partie d’un parcours réussi.',
  'Tu peux demander de l’aide et rester pleinement méritante de ta réussite.',
  'Une difficulté répétée mérite une nouvelle stratégie, pas de l’autocritique.',
  'Continue à chercher ce qui fonctionne pour toi.',
  'Tu es autorisée à apprendre de manière imparfaite.',
  'La persévérance n’est pas de tout supporter : c’est de continuer intelligemment.',
  'Un obstacle n’est pas une conclusion.',
  'Rater une fois ne dit rien sur la prochaine tentative.',
  'Même un petit retour après une pause est une victoire.',
  'Tu peux être fière de ne pas avoir renoncé à toi-même.',
  'N’oublie pas de compter ce que tu as terminé, pas seulement ce qu’il reste.',
  'Une page comprise mérite déjà un petit “bien joué”.',
  'Tu viens d’ouvrir l’application : c’est déjà un signal que tu prends soin de tes études.',
  'Chaque tâche cochée est une petite victoire réelle.',
  'Tu as le droit de célébrer les progrès que personne d’autre ne remarque.',
  'Avoir commencé est déjà mieux qu’avoir attendu le moment parfait.',
  'Une bonne question posée est une avancée.',
  'Une fiche terminée aujourd’hui, c’est du stress en moins plus tard.',
  'Même dix minutes de travail peuvent mériter ta fierté.',
  'Tu peux être contente d’avoir fait “un peu” : un peu n’est pas rien.',
  'Reconnais tes efforts avant de chercher ce que tu peux améliorer.',
  'Chaque fois que tu choisis de t’y remettre, tu gagnes quelque chose.',
  'Finir une petite tâche peut être exactement la victoire dont tu avais besoin.',
  'Tu as appris quelque chose aujourd’hui que tu ne savais pas hier.',
  'Un bureau rangé, une fiche prête, un chapitre relu : les petites choses comptent.',
  'Tu n’as pas besoin d’attendre un diplôme pour être fière de toi.',
  'Le travail invisible d’aujourd’hui prépare les réussites visibles de demain.',
  'Une journée productive peut commencer par une seule case cochée.',
  'Ton effort mérite d’être reconnu, même quand le résultat n’est pas encore là.',
  'Tu peux finir ta journée en te demandant ce qui a bien marché, pas seulement ce qui manque.',
  'Prends deux secondes pour remarquer ce que tu viens d’accomplir.',
  'Chaque mini-victoire donne un peu plus de confiance à la suivante.',
  'Tu as avancé dès l’instant où tu as choisi de ne pas abandonner.',
  'Le chemin se construit avec ces petites choses que tu fais presque sans les compter.',
  'Aujourd’hui, donne autant de valeur à tes progrès qu’à tes objectifs.',
  'Tu peux vouloir réussir et rester douce avec toi-même.',
  'Ton bien-être fait partie de ta réussite.',
  'Dormir suffisamment est aussi une façon de préparer demain.',
  'Manger, boire et faire une pause ne sont pas du temps perdu.',
  'Tu as le droit d’avoir une vie en dehors de tes études.',
  'La réussite ne vaut pas de te traiter comme une machine.',
  'Tu peux travailler sérieusement sans te parler durement.',
  'Ta santé et ton énergie sont des ressources à protéger.',
  'Une vraie pause peut te rendre plus efficace qu’une heure de travail épuisé.',
  'Tu as le droit de fermer tes cours quand la journée est terminée.',
  'Le repos n’annule pas ton ambition.',
  'Tu peux être exigeante avec tes objectifs et bienveillante avec toi-même.',
  'Ton meilleur travail vient rarement de la panique permanente.',
  'Accorde-toi les mêmes encouragements que tu donnerais à une amie.',
  'Tu mérites une réussite qui ne te détruit pas en chemin.',
  'Il est possible de viser haut sans se rabaisser à chaque erreur.',
  'Ton cerveau a aussi besoin de moments où il ne produit rien.',
  'Prendre soin de toi aujourd’hui peut améliorer ta concentration demain.',
  'Tu n’es pas obligée de mériter ton repos : tu en as simplement besoin.',
  'Une soirée tranquille peut faire partie d’une bonne stratégie de travail.',
  'Tu peux être sérieuse dans tes études sans être sévère avec toi-même.',
  'Ce que tu ressens mérite d’être écouté autant que ta liste de tâches.',
  'Ta réussite compte, mais toi aussi.',
  'Il y a de la force dans le fait de connaître ses limites.',
  'Construis une réussite dont tu auras envie de profiter.',
];
